### ISSUE TITLE
Can't make a second global identifier

### ISSUE THREAD

**Issue by sporto** [rmosolgo/graphql-relay-ruby#12]
In Rails: Each time I make a change in my code (anywhere in the rails app) I get `Can't make a second global identifier`.

I am forced to restart the server. So something related to the singleton here https://github.com/rmosolgo/graphql-relay-ruby/blob/master/lib/graphql/relay/global_node_identification.rb and rails reloading constants

**Comment by rmosolgo** [comment]
Ah, I kept running into that too, I was meaning to fix it. Here we go: add71ed

Thanks for reporting this!

**Comment by sporto** [comment]
Great, thanks, could you publish this to rubygems? thanks

**Comment by rmosolgo** [comment]
sure, i just pushed 0.4.5!
