### ISSUE TITLE
Does order belong in RelationConnection?

### ISSUE THREAD

**Issue by sgwilym** [rmosolgo/graphql-relay-ruby#19]
I was pretty surprised to find that the `order` argument on connection isn't actually part of the Relay spec! That said, now that I know, it kind of makes me question the inclusion of the `order` argument on `RelationConnection`. I've been working on a project where we'd like to do ordering with another enum type in the graph as arguments, but because those constants don't translate to columns (e.g `user.SALES_ASC` is just nonsense), we're kind of forced to write a custom connection implementation where we could otherwise handle things in the resolve block.

Any thoughts on this?

**Comment by rmosolgo** [comment]
:+1: to remove it, I guess thought it would "convenient" but I removed it in my code, too!

I added an argument with a different name that picked enum values, like you said, then I deleted that one from the fields hash.

**Comment by sgwilym** [comment]
Hey, sorry for dragging my heels on this! When I took a look at removing `order` I saw that it was wound up with how cursors are made — any preferred way you'd like to see that handled if `order` goes out?

**Comment by sgwilym** [comment]
https://github.com/rmosolgo/graphql-relay-ruby/pull/31
