### ISSUE TITLE
Cursor value isn't casted to correct type when used as WHERE constraint, may lead to inconsistent returned data

### ISSUE THREAD

**Issue by kristianm** [rmosolgo/graphql-relay-ruby#20]
When restoring the cursor value from a ``before`` or ``after`` cursor constraint, it's treated as a string. This can lead to inconsistencies in the returned data.

In our case, we paginated over a DateTime attribute. The rails data type is always time zone aware, and when casted to a string the time zone designator is incluced, like:

``"2016-02-05 16:14:34 +0100"``

When fetching data for the next page, this is used as a string when generating the WHERE constraint, which leads to a query looking like:

``AND (`comments`.`published_at` < '2016-02-05 16:14:34 +0100')``

In our case this lead to inconsistent data returned, because rails stores datetimes in UTC format in the database and mysql doesn't seem to take time zone designator into account. A typical rails query where the datetime value had been type casted correctly, would have looked like:

``AND (`comments`.`published_at` < '2016-02-05 15:14:34.000000')``
That is, converted the datetime value with timezone to UTC format.

I did [a fix for this in my fork](https://github.com/kristianm/graphql-relay-ruby/commit/3d533938dfe3ce13447a14c32e9586243c446ad6), but since I'm not totally sure about rails internals I haven't made a PR. Also, the type casting is different in rails < 4.2 so it has to be taken into account if supporting previous rails versions.

**Comment by rmosolgo** [comment]
Thanks for reporting this issue! How about opening a PR with that fix? (Or, if it's OK with you, I can open it.)

CI runs tests on [a bunch of different Rails versions](https://github.com/rmosolgo/graphql-relay-ruby/tree/master/gemfiles), so we'll see if it works!  

If it doesn't work, I can go back to figure out the API on other Rails versions.

**Comment by kristianm** [comment]
I did a [PR](https://github.com/rmosolgo/graphql-relay-ruby/pull/21)

**Comment by rmosolgo** [comment]
Thanks! Like you said, the casting API is different on some older Rails versions. I'll take a look!

**Comment by kristianm** [comment]
I already covered rails < 4.2 in the PR. Just use it how you like.

**Comment by rmosolgo** [comment]
Oh, I didn't see that before, thanks! That's awesome!
