### ISSUE TITLE
Add a license to 'graphql-relay-ruby'

### ISSUE THREAD

**Issue by kdaigle** [rmosolgo/graphql-relay-ruby#35]
Hey @rmosolgo! I've started to toy with your two gems around GraphQL and noticed that this gem doesn't have a license. Would you be willing to add a license to this repository? Thanks so much for your work on these gems! :smile:

**Comment by rmosolgo** [comment]
4f2860d :tada: have fun!

**Comment by kdaigle** [comment]
Awesome! Thanks so much. If you could do a gem release, that'd be amazing too. No rush though... you've already exceeded my turnaround expectations. :smile:

**Comment by rmosolgo** [comment]
Shipped in 0.9.0!
