### ISSUE TITLE
NoMethodError (undefined method `offset' for #<Post:0x007f8c9a053e98>):

### ISSUE THREAD

**Issue by gauravtiwari** [rmosolgo/graphql-relay-ruby#38]
Hey @rmosolgo 

Getting following error in new `0.9.0` version when running comment mutation on a post. Looks like, this is what throwing the error.
https://github.com/rmosolgo/graphql-relay-ruby/blob/master/lib/graphql/relay/relation_connection.rb#L32

```ruby
   connection = GraphQL::Relay::RelationConnection.new(post, {})
   edge = GraphQL::Relay::Edge.new(comment, connection)
```

It seems now there is different way to create a connection for edges?

**Comment by rmosolgo** [comment]
The first argument to `Connection#initialize` should be a collection -- in this case, an `ActiveRecord::Relation`. I guess our changes to calculating `cursor` made that requirement more important!

You could send an AR::Relation into the connection like this: 

```ruby 
   posts = Post.where(id: post.id)
   connection = GraphQL::Relay::RelationConnection.new(posts, {})
```

Although ... now that I look at it, if the connection is a lists of `post`s, why is the edge created with a `comment`? Shouldn't it be a `post`?

**Comment by gauravtiwari** [comment]
@rmosolgo Yes, it's a single post with a list of comments. When a commentEdge is created, the `RANGE_ADD` requires the server to send the `parent` and the newly created edge. It looks like the connection now only works with a collection and not with a single `AR` record/object. 

```javascript
  getFatQuery() {
    return Relay.QL`
      fragment on CreateCommentPayload {
        commentEdge,
        post {
          comments_count
          comments
        }
    }
    `;
  }

  getConfigs() {
    return [
      {
        type: 'FIELDS_CHANGE',
        fieldIDs: {
          post: this.props.post.id,
        },
      },
      {
        type: 'RANGE_ADD',
        parentName: 'post',
        parentID: this.props.post.id,
        connectionName: 'comments',
        edgeName: 'commentEdge',
        rangeBehaviors: {
          '': 'append',
          'order(-id)': 'prepend',
        },
      },
    ];
  }
```

**Comment by rmosolgo** [comment]
Oh, so maybe the connection should be based on the collection of `Comment`s? 

```ruby 
comments_connection = GraphQL::Relay::RelationConnection.new(post.comments, {})
new_comment_edge = GraphQL::Relay::Edge.new(comment, comments_connection)
```

**Comment by gauravtiwari** [comment]
Makes sense @rmosolgo
