### ISSUE TITLE
Relay Node Queries Broken?

### ISSUE THREAD

**Issue by bloomdido** [rmosolgo/graphql-relay-ruby#40]
Is anyone else having this problem?

    {
      node(id: "some_string") {
        id
      }
    }

results in:

    {
      "errors": [
        {
          "message": "Something went wrong during query execution: wrong number of arguments (given 2, expected 1)"
        }
      ]
    }

I have also referenced it here:

rmosolgo/graphql-ruby-demo#7
https://github.com/rmosolgo/graphql-ruby/issues/137

**Comment by rmosolgo** [comment]
Hmm, I havent seen this before, could you share your NodeIdentification configuration?

**Comment by bloomdido** [comment]
I tried it using the graphql-ruby-demo project and got the same results (figured that'd be easier than trying to post all of my code, though mine doesn't differ much from the code in the demo yet).

If you can't reproduce, let me know.

**Comment by rmosolgo** [comment]
This was caused by out-of-date code in the Demo, the fix is here: https://github.com/rmosolgo/graphql-ruby-demo/commit/2e99203cdd446c0300016bc58479dd9b642e35d3

**Comment by bloomdido** [comment]
That did it! Thanks!
