### ISSUE TITLE
Any way to make re-usable connections?

### ISSUE THREAD

**Issue by davidcelis** [rmosolgo/graphql-relay-ruby#44]
I'm working on a Graph API where three or four types will have a connection to one other type, and each connection will pretty much be exactly the same. Is there a good way of constructing a reusable connection that can be included in several types? Looking through the code and the DSL, I can't really determine if there's a way to, like a field, create a connection object that can be placed on multiple object types. Thanks in advance!

**Comment by rmosolgo** [comment]
In general, when you use `MyObjectType.connection_type`, it returns the same `GraphQL::ObjectType` each time. 

The connection type is defined once, then memoized for later use: https://github.com/rmosolgo/graphql-relay-ruby/blob/master/lib/graphql/relay/monkey_patches/base_type.rb#L3

So, you could use the same connection type over and over like this: 

```ruby 
LeafType = GraphQL::ObjectType.define do 
  # ... 
end 

TreeType = GraphQL::ObjectType.define do 
  field :leaves, LeafType.connection_type 
end 

HerbType = GraphQL::ObjectType.define do 
  field :leaves, LeafType.connection_type 
end 

ShrubType = GraphQL::ObjectType.define do 
  field :leaves, LeafType.connection_type 
end 
```

In this case, `TreeType`, `HerbType` and `ShrubType` all have a `leaves` field which returns (the same) `LeafConnection` type.

Is that a helpful answer?

**Comment by davidcelis** [comment]
@rmosolgo Yes! Thanks. I think I need to clarify one thing, though 😄 I'm specifically wondering if, for example, one of these connections has arguments and a resolver defined, are those reusable elsewhere? For instance…

```ruby
LeafType = GraphQL::ObjectType.define do
  # …
end

TreeType = GraphQL::ObjectType.define do
  connection :leaves, LeafType.connection_type
end

HerbType = GraphQL::ObjectType.define do
  connection :leaves, LeafType.connection_type do
    argument :alive, types.Boolean

    resolve -> (herb, arguments, context) do
      arguments[:alive] ? herb.leaves.alive : herb.leaves
    end
  end
end

ShrubType = GraphQL::ObjectType.define do
  connection :leaves, LeafType.connection_type
end
```

Do `ShrubType` and `TreeType` now also take an argument `:alive` and have a custom resolver? Or does only `ShrubType`? Or is that custom connection only on `HerbType`? If so, is it possible to reuse the connection that got created?

**Comment by rmosolgo** [comment]
Oh, now I think I understand! Thanks for clarifying.

> only HerbType?

Yes, only HerbType. 

The configuration is applied to the underlying GraphQL::Field,  so to share that code, you have a couple of options. 

1. __Use plain Ruby.__ Define a method which applies the field definition and call it during configuration, for example: 

   ```ruby 
   module LeavesConnection
    # Put the configuration inside this method: 
    def self.create(definition)
      definition.connection(:leaves, LeafType.connection_type) do 
        argument :alive, types.Boolean 
        resolve -> { ... } 
      end 
    end 
  end 

  ShrubType = GraphQL::ObjectType.define do 
    # Use the config helper during configuration:
    LeavesConnection.create(self) # pass the definition into that object 
  end 
  ``` 

   It's a bit weird because, within the `define { }` block, `self` is a configuration object. So you must pass that object into the method and call helpers on that config object (`config.connection`, `config.types`)   

   
2. __Use an Interface.__ If you define the field on the interface, it will be "inherited" by the implementing types. For example: 

  ```ruby 
  LeafyInterface = GraphQL::InterfaceType.define do 
    connection :leaves, LeafType.connection_type do 
      # ... custom config  
     end 
  end 

  HerbType = GraphQL::ObjectType.define do 
    interfaces [LeafyInterface]
  end 
  ```

  Now, HerbType gets the complex field definition from LeafyInterface.


Does that sound more like what you're looking for?

**Comment by davidcelis** [comment]
@rmosolgo Aha, thanks a ton! I didn't realize interfaces actually defined fields/connections that get "inherited". I thought it was just to state a requirement. Thanks so much!
