### ISSUE TITLE
Mark `clientMutationId` as an optional field

### ISSUE THREAD

**Issue by keithpitt** [rmosolgo/graphql-relay-ruby#45]
Howdy! This is probably a silly question, but is there a way to mark the clientMutationId field for mutations optional? Most other frameworks / implementations seem to have it optional by default. What do you think?

**Comment by rmosolgo** [comment]
Looking back at the spec, I see I misread that! 

> That argument must be a String. That argument may be non‐null.

You can see it's made non-null here: 

https://github.com/rmosolgo/graphql-relay-ruby/blob/master/lib/graphql/relay/mutation.rb#L113

Maybe we can make that API more flexible...

**Comment by keithpitt** [comment]
Ah right, yeah there it is. Would it be bad if we just made it nullable?

**Comment by keithpitt** [comment]
Going to close this since I opened a PR
