### ISSUE TITLE
node_identification no method error?

### ISSUE THREAD

**Issue by jasondoc3** [rmosolgo/graphql-relay-ruby#59]
I have graphl-ruby and graphql-relay-ruby in my Gemfile,in that respective order.

I get this error when trying to define the node_identification attribute on my schema

`NoMethodError: undefined method node_identification for #<GraphQL::Schema:0x007f149c028368>`

The graphql-relay-ruby is supposedly monkey patching this on, but I still was getting this error. I monkey patched it myself using the lines I found in the source. Now its working fine. Interesting though
```
class GraphQL::Schema
  attr_accessor :node_identification
end
```

**Comment by rmosolgo** [comment]
Sorry, there's a change on master that isn't on Rubygems yet, you can see the Rubygems version's readme here: https://github.com/rmosolgo/graphql-relay-ruby/blob/v0.11.2/README.md
