### ISSUE TITLE
Relay re-fetching failed… error Relay was unable to reconcile edges on a connection

### ISSUE THREAD

**Issue by Slimerkhb** [rmosolgo/graphql-relay-ruby#61]
When re-fetch data with the updated variables -- using _relay.setVariables()_ -- I get the error "**Relay was unable to reconcile edges on a connection. This most likely occurred while trying to handle a server response that includes connection edges with nodes that lack anid field.**" and Relay storage is not updated although the data come correct...

for full question with code (Ruby + ES6) see http://stackoverflow.com/questions/38495083/relay-re-fetching-failed-error-relay-was-unable-to-reconcile-edges-on-a-conne

**Comment by TsungLeo** [comment]
+1, also I have the same problem

**Comment by AnthonyDS** [comment]
+1, I'am too

**Comment by rmosolgo** [comment]
Could you post your graphql & graphql-relay versions, and maybe the queries that get sent before the error? I'm not sure where to look!

**Comment by Slimerkhb** [comment]
gem 'graphql', '0.16.0'
gem 'graphql-relay', '0.11.2'

complete information with the code provided on [stackoverflow.com](http://stackoverflow.com/questions/38495083/relay-re-fetching-failed-error-relay-was-unable-to-reconcile-edges-on-a-conne)

wherein the query fails:

> "{"query":"query MainApp_MainRelayQL($id_0:ID!) { node(id:$id_0) { ...F0 }}fragment F0 on FrontApp { _bips3ZiT3h:bips(filters:"{"browse":"most_followed","location":{"city":null,"country_name":null,"country_iso":null},"date":null,"funds":{"sum":null,"currency":null},"category":null}") { _almostRaised4C4V5f:almostRaised(first:10,limit:10) { edges { node { id, bid, title_name, about, category, financialInfo { full_cost, fund_collected, id }, logo { url, id }, location { country, id } }, cursor }, pageInfo { hasNextPage, hasPreviousPage } }, _mostRecent3Negxk:mostRecent(first:10,limit:10) { edges { node { id, bid, title_name, about, category, financialInfo { full_cost, fund_collected, id }, logo { url, id }, location { country, id } }, cursor }, pageInfo { hasNextPage, hasPreviousPage } }, _mostPopular4xo0ah:mostPopular(first:10,limit:10) { edges { node { id, bid, title_name, about, category, financialInfo { full_cost, fund_collected, id }, logo { url, id }, location { country, id } }, cursor }, pageInfo { hasNextPage, hasPreviousPage } }, id }, id}","variables":{"id_0":"RnJvbnRBcHAtezppZD0+Im1haW4ifQ=="}}"

**Comment by rmosolgo** [comment]
I tried to prettify the query, is that right that `filters:` is a string of JSON ? 

```graphql 
query MainApp_MainRelayQL($id_0: ID!) {
  node(id: $id_0) {
    ...F0
  }
}

fragment F0 on FrontApp {
  _bips3ZiT3h: bips(filters: "{\"browse\":\"most_followed\",\"location\":{\"city\":null,\"country_name\":null,\"country_iso\":null},\"date\":null,\"funds\":{\"sum\":null,\"currency\":null},\"category\":null}") {
    _almostRaised4C4V5f: almostRaised(first: 10, limit: 10) {
      edges {
        node {
          id
          bid
          title_name
          about
          category
          financialInfo {
            full_cost
            fund_collected
            id
          }
          logo {
            url
            id
          }
          location {
            country
            id
          }
        }
        cursor
      }
      pageInfo {
        hasNextPage
        hasPreviousPage
      }
    }
    _mostRecent3Negxk: mostRecent(first: 10, limit: 10) {
      edges {
        node {
          id
          bid
          title_name
          about
          category
          financialInfo {
            full_cost
            fund_collected
            id
          }
          logo {
            url
            id
          }
          location {
            country
            id
          }
        }
        cursor
      }
      pageInfo {
        hasNextPage
        hasPreviousPage
      }
    }
    _mostPopular4xo0ah: mostPopular(first: 10, limit: 10) {
      edges {
        node {
          id
          bid
          title_name
          about
          category
          financialInfo {
            full_cost
            fund_collected
            id
          }
          logo {
            url
            id
          }
          location {
            country
            id
          }
        }
        cursor
      }
      pageInfo {
        hasNextPage
        hasPreviousPage
      }
    }
    id
  }
  id
}

```

**Comment by Slimerkhb** [comment]
yes... on a server-side filters string is parsed to ruby hash

**Comment by Slimerkhb** [comment]
no solutions? :(
can you tell where i can find @relay directive documentation (options, examples etc.) ?  i can't find neither google nor other search engines

**Comment by rmosolgo** [comment]
I looked through it but couldn't find any obvious issue. I [requested the source for `TipShowType`](http://stackoverflow.com/questions/38495083/relay-re-fetching-failed-error-relay-was-unable-to-reconcile-edges-on-a-conne#comment64636720_38495083), since I _think_ that's the type inside the `edge` which has a problem

**Comment by Slimerkhb** [comment]
`TipShowType = GraphQL::ObjectType.define do
	name 'TipShow'
	description 'Tip content'
	interfaces [NodeIdentification.interface]
	global_id_field :id

	field :bid, !types.Int do
		resolve -> (obj, args, ctx) {
			obj.id
		}
	end
	field :biptype, types.Int
	field :title_name, types.String
	field :category, types.String
	field :subcategory, types.String do
		name 'subcategory'
		resolve -> (obj, args, ctx) {
			obj.bip_type.desc
		}
	end
	field :location, LocationType do
		resolve -> (obj, args, ctx) {
			obj
		}
	end
	field :about, types.String
	field :gratitude, types.String
	field :images, types.String
	field :videos, types.String
	field :draft_description, types.String
	field :description, &TipDescriptionsList

	# creator fields
	field :creator, TipCreatorType do
		resolve -> (obj, args, ctx) {
			obj
		}
	end

	# datetime fields
	field :start_date, types.String
	field :exp_date, types.String
	field :completed_date, types.String
	field :published_at, types.String
	field :updated_at, types.String do
		resolve -> (obj, args, ctx) {
			obj.updated_at.to_i
		}
	end
	field :created_at, types.Int do
		name 'created_at'
		resolve -> (obj, args, ctx) {
			obj.created_at.to_i
		}
	end
	field :days_left, types.Int do
		name 'days_left'
		resolve -> (obj, args, ctx) {
			days_left = ((obj.exp_date.to_time.to_i - Time.zone.now.to_i) / 1.day + 1).to_i
			days_left = 0 unless days_left > 0
			days_left
		}
	end

	# social fields
	field :socials, TipSocialsType do
		resolve -> (obj, args, ctx) {
			obj
		}
	end

	# financial fields
	field :pay_processor, types.String
	field :financialInfo, TipFinancialInfoType do
		resolve -> (obj, args, ctx) {
			obj
		}
	end
	field :plan, FundraisingPlanType, property: :pay_processor do
		resolve -> (obj, args, ctx) {
			obj.pay_info.fundraising_plan
		}
	end

	# lists
	field :followers, &TipFollowersList
	field :donators, TipDonatorsType do
		resolve -> (obj, args, ctx) {
			obj
		}
	end
	field :logo, TipLogoType do
		resolve -> (obj, args, ctx) {
			obj
		}
	end
	field :background, types.String do
		argument :size, types.String
		resolve -> (obj, args, ctx) {
			case args['size']
				when 'large'
					obj.bg.large.url
				else
					obj.bg.url
			end
		}
	end
	field :states, TipStatesType do
		resolve -> (obj, args, ctx) {
			obj.bip_state
		}
	end
	field :notifications_status, TipNotificationsStatusType do
		resolve -> (obj, args, ctx) {
			obj.notify_status
		}
	end
	connection :comments, TipCommentsConnectionType do
		argument :order, OrderingEnum, default_value: 'desc'
		resolve -> (obj, args, ctx) {
			obj.comments.order(created_at: args[:order])
		}
	end

	field :reward, TipRewardType do
		argument :id, !types.Int
		resolve -> (obj, args, ctx) {
			obj.rewards.where(id: args[:id]).first
		}
	end

	connection :rewards, TipRewardsConnectionType do
		resolve -> (obj, args, ctx) {
			obj.rewards.order(price: :asc)
		}
	end

	field :currentUser, UserType do
		argument :uid, !types.Int, 'User ID'
		resolve -> (obj, args, ctx) {
			::User.find_by(id: args[:uid]) if args[:uid]
		}
	end

	connection :regions, RegionsConnectionType do
		resolve ->(obj, args, ctx){
			::DeliveryRegion.order(:region)
			# args[:id].present? ? About::Menu.where(id: args[:id]).includes(:content) : About::Menu.includes(:content).order(:id)
		}
	end
end`

**Comment by rmosolgo** [comment]
@TsungLeo or @AnthonyDS  can you share details of your type which is having this error? 

My only thought right now is that it may be a mismatch between classname and type name? Some of GraphQL::Relay's defaults assume that the type name is the same as the class name, but that might not be true for `"TipShow"`!

**Comment by Slimerkhb** [comment]
I solve this problem over the mutations with FIELDS_CHANGE behavior

**Comment by rmosolgo** [comment]
Could you describe the change you made? It sounds like this may be a common problem, so others may want to hear your solution!

**Comment by Slimerkhb** [comment]
Solution of this problem (including code) you can see on http://stackoverflow.com/posts/38495083/revisions [http://stackoverflow.com/posts/38495083/revisions]

**Comment by voxmatt** [comment]
I'm having this same problem but it's outside a mutation; so @Slimerkhb's answer isn't all that helpful.

**Comment by rmosolgo** [comment]
@voxmatt this issue is loaded with a lot of (hard-to-follow) history and relates to a very old gem version. Would you mind opening a fresh issue for the problem you encountered?
